### ISSUE TITLE
Loading bio text causes errors

### ISSUE THREAD

**Issue by ghost** [flatterline/jekyll-plugins#1]
Hello,

While using team.rb I noticed that the plugin is very sensitive to the type of text that goes into the bio field.  I believe it is an issue with syck.rb.  For example, the following yaml gives an error:
active: true
bio:
Testing the bio in 2007.
email: test@test.com
<snip>

.rvm/rubies/ruby-1.9.2-p290/lib/ruby/1.9.1/syck.rb:135:in `load': syntax error on line 3, col 0:`email: test@test.com' (ArgumentError)

**Comment by curtis** [comment]
We're using fairly complicated [team YML files](https://github.com/flatterline/flatterline.com/tree/master/_team) for our own site and haven't seen anything like this.

I'm not sure if GitHub removed the indentation of the bio text, but if not, YAML requires indentation to determine scope. So it should look like this in your YAML file:

```
active: true
bio:
  Testing the bio in 2007.
email: test@test.com
```

Let me know if that helps. Thanks!

**Comment by ghost** [comment]
Aha.  The indentation fixed it.  Thakns Curtis.

**Comment by curtis** [comment]
You're welcome! Glad that fixed it :)
