### ISSUE TITLE
The _team directory

### ISSUE THREAD

**Issue by akshaysmurthy** [flatterline/jekyll-plugins#2]
Where exactly should I put the **_team** directory into?  the source directory or the project directory?

If you look at line 53 of team.rb - 

  **if Dir.exists?('_team')
            Dir.chdir('_team')**

It's actually looking for the _team directory in the project directory.

So I put it in the project directory.

But at line 36 - 

  **self.data = YAML.load(File.read(File.join(@base, path)))**

Here it tries to join the source directory (**@base**) and **_team/some-profile.yml**

But that directory does not exist!

**Comment by curtis** [comment]
@iamakshay it should be in the root of your jekyll project. See https://github.com/flatterline/flatterline.com to see how we set up the structure of our site.

Let me know if that helps!
