### ISSUE TITLE
Change project layout name

### ISSUE THREAD

**Issue by flowerett** [flatterline/jekyll-plugins#3]
I've just realized that I can change **portfolio** layout name in:

``` ruby
self.read_yaml(File.join(base, '_layouts'), 'awesome-portfolio.html')
```

but how can I customize filename for the **project.html** layout?

**Comment by flowerett** [comment]
I's quite easy!  The only thing I need is to change **layout** setting in the *.yml file!

**Comment by curtis** [comment]
@flowerett glad you were able to find it!
